language: node_js
node_js:
    - '10'
cache:
    yarn: true
    directories:
        - 'node_modules'
before_script:
    - yarn run lerna bootstrap
    - git checkout .
script:
    - yarn run lint
    - yarn test
    - yarn run snapshot
before_deploy:
    - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" >> $HOME/.npmrc
deploy:
    provider: script
    script: 'yarn run lerna:publish'
    skip_cleanup: true
    on:
        node: '10'
        branch: master
        condition: $TRAVIS_COMMIT_MESSAGE =~ ^Publish
